#!/usr/bin/env node

import fs from "fs";
import path from "path";
import inquirer from "inquirer";
import { execSync } from "child_process";

function detectPackageManager(): "npm" | "yarn" | "pnpm" {
  const userAgent = process.env.npm_config_user_agent;

  if (userAgent) {
    if (userAgent.startsWith("yarn")) {
      return "yarn";
    } else if (userAgent.startsWith("pnpm")) {
      return "pnpm";
    }
  }
  return "npm";
}

function installPackages(
  projectDir: string,
  packages: string[],
  isDev: boolean = false,
  packageManager: "npm" | "yarn" | "pnpm"
) {
  try {
    let command = "";
    const packageList = packages.map((pkg) => `${pkg}@latest`).join(" ");

    if (packageManager === "yarn") {
      const devFlag = isDev ? "--dev" : "";
      command = `yarn add ${packageList} ${devFlag}`;
    } else if (packageManager === "pnpm") {
      const devFlag = isDev ? "--save-dev" : "";
      command = `pnpm add ${packageList} ${devFlag}`;
    } else {
      const devFlag = isDev ? "--save-dev" : "";
      command = `npm install ${packageList} ${devFlag}`;
    }

    console.log(`Installing ${isDev ? "dev dependencies" : "dependencies"}...`);
    execSync(command, {
      cwd: projectDir,
      stdio: "inherit",
    });
    console.log(`Installed ${packages.join(", ")}`);
  } catch (error) {
    console.error(`Failed to install packages:`, error);
    throw error;
  }
}

async function initProject() {
  const commandLineProjectName = process.argv[2];

  const packageManager = detectPackageManager();

  const questions: any[] = [];

  if (!commandLineProjectName) {
    questions.push({
      type: "input",
      name: "projectName",
      message: "Enter your project name:",
      validate: (input: string) => {
        if (!input) return "Project name cannot be empty";
        return /^[a-z0-9\-]+$/.test(input)
          ? true
          : "Use only lowercase letters, numbers, and hyphens";
      },
    });
  } else {
    // Validate command line project name
    if (!/^[a-z0-9\-]+$/.test(commandLineProjectName)) {
      console.error(
        "❌ Project name must use only lowercase letters, numbers, and hyphens"
      );
      process.exit(1);
    }
  }

  questions.push({
    type: "list",
    name: "language",
    message: "Choose server language:",
    choices: ["JavaScript", "TypeScript"],
  });

  const answers = await inquirer.prompt(questions);

  const projectName = commandLineProjectName || answers.projectName;
  const { language } = answers;
  const projectDir = path.join(process.cwd(), projectName);

  // Create project main folder
  if (!fs.existsSync(projectDir)) {
    fs.mkdirSync(projectDir);
    console.log(`Created project folder: ${projectName}`);
  } else {
    console.log(
      `\n❌ Folder ${projectName} already exists. \n\nPlease choose a different project name or remove the existing folder`
    );
    process.exit(1);
  }

  // Create basic package.json
  const packageJsonContent: any = {
    name: projectName,
    version: "1.0.0",
    description:
      "A basic Express server generated by create-basic-express-server",
    main: "server.js",
    type: "module",
    scripts:
      language === "TypeScript"
        ? {
            start: "tsc && node dist/server.js",
            dev: 'nodemon --exec "npm run start" --ext ts watch src || exit 1',
          }
        : { start: "node src/server.js", dev: "nodemon src/server.js" },
    author: "",
    license: "ISC",
  };

  const packageJsonPath = path.join(projectDir, "package.json");
  if (!fs.existsSync(packageJsonPath)) {
    fs.writeFileSync(
      packageJsonPath,
      JSON.stringify(packageJsonContent, null, 2)
    );
  }

  // .gitignore
  const gitignoreContent = `node_modules
.env
dist
`;
  const gitignorePath = path.join(projectDir, ".gitignore");
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, gitignoreContent);
  }

  // .env file
  const envContent = `PORT=3000`;
  const envPath = path.join(projectDir, ".env");
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent);
  }

  // tsconfig.json
  if (language === "TypeScript") {
    const tsconfigContent = {
      compilerOptions: {
        target: "ES2020",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        rootDir: "src",
        outDir: "dist",
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        strict: true,
        skipLibCheck: true,
      },
    };
    const tsconfigPath = path.join(projectDir, "tsconfig.json");
    if (!fs.existsSync(tsconfigPath)) {
      fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfigContent, null, 2));
    }
  }

  const srcPath = path.join(projectDir, "src");
  if (!fs.existsSync(srcPath)) {
    fs.mkdirSync(srcPath);
  }

  const subfolders =
    language === "TypeScript"
      ? ["controllers", "middlewares", "models", "types", "utils"]
      : ["controllers", "middlewares", "models", "utils"];

  subfolders.forEach((folder) => {
    const folderPath = path.join(srcPath, folder);
    if (!fs.existsSync(folderPath)) {
      fs.mkdirSync(folderPath);
    }
  });

  const serverFileName = language === "TypeScript" ? "server.ts" : "server.js";
  const serverFilePath = path.join(srcPath, serverFileName);
  let serverCode = "";

  if (language === "TypeScript") {
    serverCode = `import express, { Request, Response } from 'express';
import { config } from "dotenv";
import cors from "cors";


config({
  path: "./.env",
});
const PORT = process.env.PORT || 3000;

const app = express();
app.use(cors())
app.use(express.json());


app.get('/', (req: Request, res: Response) => {
  res.send('Welcome to the backend! Where we make the internet tick!');
});

app.listen(PORT, () => {
  console.log(\`Server is running on port \${PORT}\`);
});
`;
  } else {
    serverCode = `import express from "express";
import { config } from "dotenv";

config({
  path: "./.env",
});

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {
  res.send('Welcome to the backend! Where we make the internet tick!');
});

app.listen(PORT, () => {
  console.log(\`Server is running on port \${PORT}\`);
});
`;
  }

  if (!fs.existsSync(serverFilePath)) {
    fs.writeFileSync(serverFilePath, serverCode);
  }

  try {
    // Prepare package lists
    const prodPackages = ["express", "dotenv", "cors"];
    const devPackages = ["nodemon"];

    if (language === "TypeScript") {
      devPackages.push(
        "@types/node",
        "typescript",
        "@types/express",
        "@types/cors"
      );
    }

    installPackages(projectDir, prodPackages, false, packageManager);

    installPackages(projectDir, devPackages, true, packageManager);

    console.log("\n✅ Project setup complete!");
  } catch (error) {
    console.error("\n❌ Error during package installation");
  }
}

initProject().catch((error) => {
  console.error("Error initializing project:", error);
});
